{
  "abstract" : [
    {
      "text" : "Implementation of gesture recognizer delegate method. Controls whether a gesture recognizer should continue to",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "track events. This is always the case when in absolute mode (original behavior), but in relative mode it is only",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "allowed until the handle has moved a meaningful amount.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView",
        "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView",
        "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView\/UIGestureRecognizerDelegate-Implementations"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView\/gestureRecognizerShouldBegin(_:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@CM@JoyStickView@objc(cs)JoyStickView(im)gestureRecognizerShouldBegin:",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "gestureRecognizerShouldBegin"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:objc(cs)UIGestureRecognizer",
        "text" : "UIGestureRecognizer"
      },
      {
        "kind" : "text",
        "text" : ") -> "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:Sb",
        "text" : "Bool"
      }
    ],
    "modules" : [
      {
        "name" : "JoyStickView"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "gestureRecognizerShouldBegin:"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Method",
    "symbolKind" : "method",
    "title" : "gestureRecognizerShouldBegin(_:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "override"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "gestureRecognizerShouldBegin"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "gestureRecognizer"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:objc(cs)UIGestureRecognizer",
              "text" : "UIGestureRecognizer"
            },
            {
              "kind" : "text",
              "text" : ") -> "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:Sb",
              "text" : "Bool"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "kind" : "parameters",
      "parameters" : [
        {
          "content" : [
            {
              "inlineContent" : [
                {
                  "text" : "the gesture recognizer being queried",
                  "type" : "text"
                }
              ],
              "type" : "paragraph"
            }
          ],
          "name" : "gestureRecognizer"
        }
      ]
    },
    {
      "content" : [
        {
          "anchor" : "return-value",
          "level" : 2,
          "text" : "Return Value",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "true if the gesture recognizer can continue to track events",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/joystickview\/joystickview\/gesturerecognizershouldbegin(_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/joystickview\/joystickview\/gesturerecognizershouldbegin(_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.braysoft.JoyStickView/documentation/JoyStickView": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "JoyStickView",
  "type" : "topic",
  "url" : "\/documentation\/joystickview"
},
"doc://com.braysoft.JoyStickView/documentation/JoyStickView/JoyStickView": {
  "abstract" : [
    {
      "text" : "A simple implementation of a joystick interface like those found on classic arcade games. This implementation detects",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "and reports two values when the joystick moves:",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "JoyStickView"
    }
  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "JoyStickView"
    }
  ],
  "role" : "symbol",
  "title" : "JoyStickView",
  "type" : "topic",
  "url" : "\/documentation\/joystickview\/joystickview"
},
"doc://com.braysoft.JoyStickView/documentation/JoyStickView/JoyStickView/UIGestureRecognizerDelegate-Implementations": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView\/UIGestureRecognizerDelegate-Implementations",
  "kind" : "article",
  "role" : "collectionGroup",
  "title" : "UIGestureRecognizerDelegate Implementations",
  "type" : "topic",
  "url" : "\/documentation\/joystickview\/joystickview\/uigesturerecognizerdelegate-implementations"
},
"doc://com.braysoft.JoyStickView/documentation/JoyStickView/JoyStickView/gestureRecognizerShouldBegin(_:)": {
  "abstract" : [
    {
      "text" : "Implementation of gesture recognizer delegate method. Controls whether a gesture recognizer should continue to",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "track events. This is always the case when in absolute mode (original behavior), but in relative mode it is only",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "allowed until the handle has moved a meaningful amount.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "gestureRecognizerShouldBegin"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIGestureRecognizer",
      "text" : "UIGestureRecognizer"
    },
    {
      "kind" : "text",
      "text" : ") -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView\/gestureRecognizerShouldBegin(_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "gestureRecognizerShouldBegin:"
    }
  ],
  "role" : "symbol",
  "title" : "gestureRecognizerShouldBegin(_:)",
  "type" : "topic",
  "url" : "\/documentation\/joystickview\/joystickview\/gesturerecognizershouldbegin(_:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Instance Method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "gestureRecognizerShouldBegin:"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "gestureRecognizerShouldBegin:"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "text",
                  "text" : "- ("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@T@BOOL",
                  "text" : "BOOL"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "kind" : "identifier",
                  "text" : "gestureRecognizerShouldBegin:"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)UIGestureRecognizer",
                  "text" : "UIGestureRecognizer"
                },
                {
                  "kind" : "text",
                  "text" : " *) "
                },
                {
                  "kind" : "internalParam",
                  "text" : "gestureRecognizer"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView\/title",
        "value" : "JoyStickView"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "JoyStickView"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView~1gestureRecognizerShouldBegin(_:)\/title",
        "value" : "gestureRecognizerShouldBegin:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView~1gestureRecognizerShouldBegin(_:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "gestureRecognizerShouldBegin:"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}