{
  "abstract" : [
    {
      "text" : "Install an Obj-C block that will receive the polar coordinates of the joystick.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView",
        "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView\/setPolarMonitor(_:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "extendedModule" : "JoyStickView",
    "externalID" : "c:@CM@JoyStickView@objc(cs)JoyStickView(im)setPolarMonitor:",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "setPolarMonitor"
      },
      {
        "kind" : "text",
        "text" : "(("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:14CoreFoundation7CGFloatV",
        "text" : "CGFloat"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:14CoreFoundation7CGFloatV",
        "text" : "CGFloat"
      },
      {
        "kind" : "text",
        "text" : ") -> "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s4Voida",
        "text" : "Void"
      },
      {
        "kind" : "text",
        "text" : ")"
      }
    ],
    "modules" : [
      {
        "name" : "JoyStickView"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "setPolarMonitor:"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Method",
    "symbolKind" : "method",
    "title" : "setPolarMonitor(_:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "attribute",
              "text" : "@objc"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "setPolarMonitor"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "block"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "attribute",
              "text" : "@escaping"
            },
            {
              "kind" : "text",
              "text" : " ("
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:14CoreFoundation7CGFloatV",
              "text" : "CGFloat"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:14CoreFoundation7CGFloatV",
              "text" : "CGFloat"
            },
            {
              "kind" : "text",
              "text" : ") -> "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s4Voida",
              "text" : "Void"
            },
            {
              "kind" : "text",
              "text" : ")"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "kind" : "parameters",
      "parameters" : [
        {
          "content" : [
            {
              "inlineContent" : [
                {
                  "text" : "the block to install. It must expect two CGFloat values, first being the angle, and the second",
                  "type" : "text"
                },
                {
                  "text" : " ",
                  "type" : "text"
                },
                {
                  "text" : "being the displacement",
                  "type" : "text"
                }
              ],
              "type" : "paragraph"
            }
          ],
          "name" : "block"
        }
      ]
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/joystickview\/joystickview\/setpolarmonitor(_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/joystickview\/joystickview\/setpolarmonitor(_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.braysoft.JoyStickView/documentation/JoyStickView": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "JoyStickView",
  "type" : "topic",
  "url" : "\/documentation\/joystickview"
},
"doc://com.braysoft.JoyStickView/documentation/JoyStickView/JoyStickView": {
  "abstract" : [
    {
      "text" : "A simple implementation of a joystick interface like those found on classic arcade games. This implementation detects",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "and reports two values when the joystick moves:",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "JoyStickView"
    }
  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "JoyStickView"
    }
  ],
  "role" : "symbol",
  "title" : "JoyStickView",
  "type" : "topic",
  "url" : "\/documentation\/joystickview\/joystickview"
},
"doc://com.braysoft.JoyStickView/documentation/JoyStickView/JoyStickView/setPolarMonitor(_:)": {
  "abstract" : [
    {
      "text" : "Install an Obj-C block that will receive the polar coordinates of the joystick.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "setPolarMonitor"
    },
    {
      "kind" : "text",
      "text" : "(("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:14CoreFoundation7CGFloatV",
      "text" : "CGFloat"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:14CoreFoundation7CGFloatV",
      "text" : "CGFloat"
    },
    {
      "kind" : "text",
      "text" : ") -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s4Voida",
      "text" : "Void"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView\/setPolarMonitor(_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "setPolarMonitor:"
    }
  ],
  "role" : "symbol",
  "title" : "setPolarMonitor(_:)",
  "type" : "topic",
  "url" : "\/documentation\/joystickview\/joystickview\/setpolarmonitor(_:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Instance Method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "setPolarMonitor:"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "setPolarMonitor:"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "text",
                  "text" : "- ("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:v",
                  "text" : "void"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "kind" : "identifier",
                  "text" : "setPolarMonitor:"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:BFv(#d#d)",
                  "text" : "void (^)(double, double)"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "kind" : "internalParam",
                  "text" : "block"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView\/title",
        "value" : "JoyStickView"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "JoyStickView"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView~1setPolarMonitor(_:)\/title",
        "value" : "setPolarMonitor:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView~1setPolarMonitor(_:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "setPolarMonitor:"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}