{
  "abstract" : [
    {
      "text" : "User removed touch from display. Move joystick to center of base.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView",
        "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView\/touchesEnded(_:with:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@CM@JoyStickView@objc(cs)JoyStickView(im)touchesEnded:withEvent:",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "touchesEnded"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:Sh",
        "text" : "Set"
      },
      {
        "kind" : "text",
        "text" : "<"
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:objc(cs)UITouch",
        "text" : "UITouch"
      },
      {
        "kind" : "text",
        "text" : ">, "
      },
      {
        "kind" : "externalParam",
        "text" : "with"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:objc(cs)UIEvent",
        "text" : "UIEvent"
      },
      {
        "kind" : "text",
        "text" : "?)"
      }
    ],
    "modules" : [
      {
        "name" : "JoyStickView"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "touchesEnded:withEvent:"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Method",
    "symbolKind" : "method",
    "title" : "touchesEnded(_:with:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "override"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "touchesEnded"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "touches"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:Sh",
              "text" : "Set"
            },
            {
              "kind" : "text",
              "text" : "<"
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:objc(cs)UITouch",
              "text" : "UITouch"
            },
            {
              "kind" : "text",
              "text" : ">, "
            },
            {
              "kind" : "externalParam",
              "text" : "with"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "event"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:objc(cs)UIEvent",
              "text" : "UIEvent"
            },
            {
              "kind" : "text",
              "text" : "?)"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "kind" : "parameters",
      "parameters" : [
        {
          "content" : [
            {
              "inlineContent" : [
                {
                  "text" : "the set of UITouch instances, one for each touch event (ignored)",
                  "type" : "text"
                }
              ],
              "type" : "paragraph"
            }
          ],
          "name" : "touches"
        },
        {
          "content" : [
            {
              "inlineContent" : [
                {
                  "text" : "additional event info (ignored)",
                  "type" : "text"
                }
              ],
              "type" : "paragraph"
            }
          ],
          "name" : "event"
        }
      ]
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/joystickview\/joystickview\/touchesended(_:with:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/joystickview\/joystickview\/touchesended(_:with:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.braysoft.JoyStickView/documentation/JoyStickView": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "JoyStickView",
  "type" : "topic",
  "url" : "\/documentation\/joystickview"
},
"doc://com.braysoft.JoyStickView/documentation/JoyStickView/JoyStickView": {
  "abstract" : [
    {
      "text" : "A simple implementation of a joystick interface like those found on classic arcade games. This implementation detects",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "and reports two values when the joystick moves:",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "JoyStickView"
    }
  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "JoyStickView"
    }
  ],
  "role" : "symbol",
  "title" : "JoyStickView",
  "type" : "topic",
  "url" : "\/documentation\/joystickview\/joystickview"
},
"doc://com.braysoft.JoyStickView/documentation/JoyStickView/JoyStickView/touchesEnded(_:with:)": {
  "abstract" : [
    {
      "text" : "User removed touch from display. Move joystick to center of base.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "touchesEnded"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sh",
      "text" : "Set"
    },
    {
      "kind" : "text",
      "text" : "<"
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UITouch",
      "text" : "UITouch"
    },
    {
      "kind" : "text",
      "text" : ">, "
    },
    {
      "kind" : "externalParam",
      "text" : "with"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIEvent",
      "text" : "UIEvent"
    },
    {
      "kind" : "text",
      "text" : "?)"
    }
  ],
  "identifier" : "doc:\/\/com.braysoft.JoyStickView\/documentation\/JoyStickView\/JoyStickView\/touchesEnded(_:with:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "touchesEnded:withEvent:"
    }
  ],
  "role" : "symbol",
  "title" : "touchesEnded(_:with:)",
  "type" : "topic",
  "url" : "\/documentation\/joystickview\/joystickview\/touchesended(_:with:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Instance Method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "touchesEnded:withEvent:"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "method"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "touchesEnded:withEvent:"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "text",
                  "text" : "- ("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:v",
                  "text" : "void"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "kind" : "identifier",
                  "text" : "touchesEnded:"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:Q$objc(cs)NSSet",
                  "text" : "NSSet<UITouch *>"
                },
                {
                  "kind" : "text",
                  "text" : " *) "
                },
                {
                  "kind" : "internalParam",
                  "text" : "touches"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "withEvent:"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)UIEvent",
                  "text" : "UIEvent"
                },
                {
                  "kind" : "text",
                  "text" : " *) "
                },
                {
                  "kind" : "internalParam",
                  "text" : "event"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView\/title",
        "value" : "JoyStickView"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "JoyStickView"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView~1touchesEnded(_:with:)\/title",
        "value" : "touchesEnded:withEvent:"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.braysoft.JoyStickView~1documentation~1JoyStickView~1JoyStickView~1touchesEnded(_:with:)\/fragments",
        "value" : [
          {
            "kind" : "text",
            "text" : "- "
          },
          {
            "kind" : "identifier",
            "text" : "touchesEnded:withEvent:"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}